### ISSUE TITLE
Impossible to use RangeSlider on the MainWindow

### ISSUE THREAD

**Issue by scoute** [sleepbysleep/range_slider_for_Qt5_and_PyQt5#2]
Hi. Thanks for this custom slider, but a have a problem.
Any QButton or QSlider I can put into a verticalLayout on MainWindow,  but RangeSlider I can't.

```
...
MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
{
    ui->setupUi(this);
...

...
   RangeSlider slider(Qt::Horizontal, this);
    slider.setMinimumHeight(30);
    slider.setMinimum(0);
    slider.setMaximum(255);
    slider.setLow(15);
    slider.setHigh(35);
    slider.setTickPosition(QSlider::TicksBelow);
    slider.show();
    slider.raise();

    ui->verticalLayout->addWidget(slider, 0);
...
```

Error: No viable conversion from 'RangeSlider' to 'QWidget *'

**Comment by sleepbysleep** [comment]
That seems to be solved by converting 'ui->verticalLayout->addWidget(slider, 0);' into 'ui->verticalLayout->addWidget(&slider, 0);'.

**Comment by sleepbysleep** [comment]
> Hi. Thanks for this custom slider, but a have a problem. Any QButton or QSlider I can put into a verticalLayout on MainWindow, but RangeSlider I can't.
> 
> ```
> ...
> MainWindow::MainWindow(QWidget *parent)
>     : QMainWindow(parent)
>     , ui(new Ui::MainWindow)
> {
>     ui->setupUi(this);
> ...
> 
> ...
>    RangeSlider slider(Qt::Horizontal, this);
>     slider.setMinimumHeight(30);
>     slider.setMinimum(0);
>     slider.setMaximum(255);
>     slider.setLow(15);
>     slider.setHigh(35);
>     slider.setTickPosition(QSlider::TicksBelow);
>     slider.show();
>     slider.raise();
> 
>     ui->verticalLayout->addWidget(slider, 0);
> ...
> ```
> 
> Error: No viable conversion from 'RangeSlider' to 'QWidget *'
